### ISSUE TITLE
Feature request: change a folder of export

### ISSUE THREAD

**Issue by okunev** [ccimpoi/ChromedFigma#2]
Please, add a setting to save prototypes not to default Downloads folder. There is a mess out there so important prototype files drawn in it.

<img width="456" alt="screen shot 2018-11-23 at 11 59 02" src="https://user-images.githubusercontent.com/3657051/48935035-42467480-ef17-11e8-9a71-1142d70f6a5b.png">

**Comment by ccimpoi** [comment]
This limitation is by design because I really kept is simple on the UI side :-)
The apps generates links that have the entire html page blob in the href:
```
linkData.href = this.sanitizer.bypassSecurityTrustResourceUrl(window.URL.createObjectURL(blob));
```
and the links are programatically clicked to trigger the download.

The other option would have been to add a lot of UI in order to allow for save dialogs and also generate files instead of the blob hack.

But that would be a 2.0 which I can't commit to because this one does what needs to do.
Surprisingly Figma didn't add this but they do have PDF export now which is ok ish.
