### ISSUE TITLE
Only 10 artboards/HTML files are exported

### ISSUE THREAD

**Issue by ondrejhomola** [ccimpoi/ChromedFigma#3]
Hi ccimpoi. I really dig this plugin and it works well with figma file which has less than 10 artboards. However most of our prototypes have more than 10 artboards and the ChromefFigma plugin just ignores the rest. Is there any chance to fix it? Thank you

**Comment by ccimpoi** [comment]
Hi!

Thanks for the report!

Apparently there is a limit on programatically clicking elements at least in Chrome extensions.
Added a delay of 100 ms which is not noticeable in the UI but fixes the issue.

Please grab the 1.1.4 zip from:
https://github.com/ccimpoi/ChromedFigma/tree/master/unpacked!

**Comment by ondrejhomola** [comment]
Hi ccimpoi :) 

Thanks for all your good work! Figma should buy your plugin, because it is necessary for offline devices. Now it works almost perfectly with the export delay and back updates. However I'm getting a strange behaviour when I'm exporting 81 artboards. It exports only 77 html and then I need to search for the missing ones. Then when I find the missing ones - I need to remove X html artboards and export again. Sometimes I need to do it 2 or 3 times, to really get what I'm missing.

Any clue why is that happening?  Cheers!

**Comment by ccimpoi** [comment]
I think it s Chrome again randomly dropping link clicks when too many are triggered too fast. This turns out to be a limitation for the blob link hack ChromedFigma is using...
I added some logic to progressively increment the click delay up to 1 sec for 100 or more clicks and keep the 100 ms for 10 clicks. The idea is to limit the number of downloads at any time to try to avoid Chrome killing them.

Please try the 1.1.6 from https://github.com/ccimpoi/ChromedFigma/tree/master/unpacked and see if it works for your 81 artboards.
